- README.md
> Corrected developing command in README.md

- package-lock.json
- src/jobs/github/prRepo.js
- src/jobs/github/repo.js
- src/jobs/index.js
Created a file prRepo for cronJob which fetches 10 PR's of all repos
> Created PrRepoJob

- src/models/User.js
> added User model

- src/controllers/v1/github.js
- src/routes/v1/github.js
- src/utils/github.js
> added route to list all PRs

- src/controllers/v1/user.js
- src/routes/v1/user.js
- src/validators/user.js
> added route to update user profile

- src/controllers/v1/user.js
- src/validators/user.js
> added fields at socials route to be optional

- package-lock.json
- package.json
- src/controllers/v1/auth.js
- src/controllers/v1/github.js
- src/routes/v1/github.js
- src/utils/github.js
> added route to star and unstar a repo

- src/config/roles.js
- src/models/User.js
> added role key in User model

- src/controllers/v1/user.js
- src/middlewares/auth.js
- src/models/User.js
- src/routes/v1/user.js
> added GET / route to get all users' profiles 

- src/controllers/v1/user.js
- src/routes/v1/user.js
> added route to display profile by id

- src/models/Discussion.js
- src/models/DiscussionComment.js
> added DiscussionComment model

- src/controllers/v1/discussion.js
- src/models/Discussion.js
- src/models/DiscussionComment.js
- src/routes/v1/discussion.js
- src/routes/v1/index.js
- src/validators/discussion.js
> added POST route to post discussion

- src/controllers/v1/github.js
- src/routes/v1/github.js
- src/utils/github.js
> added route to get repo

- src/controllers/v1/discussion.js
- src/models/Discussion.js
- src/models/DiscussionComment.js
- src/routes/v1/discussion.js
- src/validators/discussion.js
> added route to post comment on a discussion

- src/controllers/v1/discussion.js
- src/routes/v1/discussion.js
> added route to get all discussions

- src/controllers/v1/discussion.js
- src/routes/v1/discussion.js
> added route to display all comments on a discussion

- src/models/SkillTestQuestion.js
> added SkillTestQuestion model

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
- src/validators/skillTest.js
> added route to update skill test

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
- src/validators/skillTest.js
> added route to update skill test question

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
> added route to delete a skill test question

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
> added route to publish a skill test

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
> added route to unpublish a skill test

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
> added route to delete a skill test

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
> added route to display all skill test questions

- src/controllers/v1/skillTest.js
- src/routes/v1/skillTest.js
> added route to display all skill tests

- src/controllers/v1/discussion.js
- src/routes/v1/discussion.js
- src/validators/discussion.js
> added reportDiscussion route

- src/controllers/v1/discussion.js
- src/models/ReportDiscussionCommentDetails.js
- src/models/ReportDiscussionDetails.js
- src/routes/v1/discussion.js
- src/validators/discussion.js
renamed ReportDiscussion -> ReportDiscussionDetails and ReportDiscuss…
> renamed some models

- src/models/ReportDiscussionCommentDetails.js
> added discussionId in ReportDiscussionCommentDetails.js

- src/models/ReportDiscussion.js
> Issue #128

- src/models/ReportDiscussionComment.js
> added ReportDiscussionComment model Schema

- src/controllers/v1/discussion.js
- src/models/ReportDiscussion.js
> Issue #127

- docs/skill-tests.md
> added first route in skill test routes

- src/controllers/v1/discussion.js
- src/models/DiscussionComment.js
> add reportsCount in DiscussionCommentSchema

- src/controllers/v1/discussion.js
- src/models/Discussion.js
> add reportsCount in the DiscussionSchema

- src/controllers/v1/skillTest.js
> remove the correctIndex field if user not an admin

- Dockerfile
> dockerfile added

- app.js
- package-lock.json
- package.json
Added rate limiter to receive 100 requests per hour from a particular IP address.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.
Please review and if any changes required let me know.
Thank you.
For issue #168
> Adding various security features issue #168

- src/controllers/v1/github.js
- src/routes/v1/github.js
- src/utils/github.js
- Created Fork API `/fork/:owner/:repo`
> Added Fork API
